server:
  port: 8103
spring:
  application:
    name: nzuul-serivce
  security:
    user:
      name: admin
      password: 123456
eureka:
  instance:
    # 多久到服务中心去续约
    lease-renewal-interval-in-seconds: 30
  client:
    # 从服务中心获取服务间隔
    registry-fetch-interval-seconds: 30
    # 将自己注册到服务中心
    register-with-eureka: true
    # 服务中心地址
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8004/eureka/
    # 是否获取别的注册的服务
    fetch-registry: true
zuul:
  routes:
    openfeign-service:
      path: /openfeign-service/**
    remote-service:
      path: /remote-service/**