server:
  port: 8101
spring:
  application:
    name: eureka-client

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8001/eureka/ #配置注册中心地址


token:
  dev: dev
  bad: bad
  dev-ip: 124.221.35.171
  dev-port: 8080

redirectUrl: www.baidu.com
