server:
  port: 8100
spring:
  security:
    user:
     name: admin
     password: 123456
  application:
    name: myopenfeign
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:123456@localhost:8004/eureka/
