server:
  port: 8100
  forward-headers-strategy: framework

spring:
  security:
    user:
     name: admin
     password: 123456
  application:
    name: openfeign-service

eureka:
  instance:
    # eureka 实例续约频率 这里是客户端所以 是Client续约频率
    lease-renewal-interval-in-seconds: 30

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:123456@localhost:8004/eureka/
    # 服务拉取频率
    registry-fetch-interval-seconds: 30

feign:
  hystrix:
    enabled: true  # 开启服务降级

logging:
  level:
    com.micro.openfeign.service.UserService: debug