server:
  port: 8864



spring:
  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
    cache: false  # 关闭缓存
  datasource:
    url: jdbc:mysql://localhost:3306/test_user


logging:
  config: classpath:log4j2/log4j2.xml


#mybatis:
#  check-config-location:


