server:
  port: 8864


datasource:
  url: localhost:3306/db0

spring:
  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
    cache: false  # 关闭缓存
  datasource:
    url: jdbc:mysql://${datasource.url}?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1142165668
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1770000
  redis:
    database: 0  # 数据库名称0-15
    host: 192.168.238.128
    port: 6379
    password: 123456
    timeout: 5000
    lettuce:
      pool:
        # 连接池中最小空闲连接数量，默认值0
        min-idle: 50
        # 连接池中最大空闲连接数量，默认值8
        max-idle: 500
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个连接数，则此时pool的状态为exhausted
        max-active: 1000
        # 等待可用连接的最大时间，单位：ms，默认-1永久等待。如果超过等待时间，抛出JedisConnectionException
        max-wait: 1
      shutdown-timeout: 100ms
  # 当服务在server上运行时，是否打印banner on off log
  main:
    banner-mode: log
  # 默认就是这个位置
  banner:
    location: classpath:banner.txt

mybatis:
  config-location:
    - classpath:mybatis.xml
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: ogr.spring.pojo.*
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰


logging:
  config: classpath:log4j2/log4j2.xml




