server:
  port: 8864


datasource:
  url: localhost:3306/db0

spring:
  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
    cache: false  # 关闭缓存
  datasource:
    url: jdbc:mysql://${datasource.url}?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1142165668
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1770000
  redis:
    database: 5
    host: 192.168.206.128
    port: 6379
    password: 123456
    timeout: 5000
    jedis:
      pool:
        # 连接池中最大空闲连接数量，默认值8
        max-idle: 500
        # 连接池中最小空闲连接数量，默认值0
        min-idle: 50
        # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted
        max-active: 1000
        # 等待可用连接的最大时间，单位毫秒，默认-1永久等待。如果超过等待时间，抛出JedisConnectionException
        max-wait: 2000


mybatis:
  config-location:
    - classpath:mybatis.xml
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: ogr.spring.pojo.*
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰


logging:
  config: classpath:log4j2/log4j2.xml



