server:
  port: 8002
spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: replica1  # 指定主机名
  client:
    register-with-eureka: true # 是否注册到服务中心（注册中心不需要开启）
    fetch-registry: true       # 是否从服务中心获取服务（注册中心不需要开启）
    service-url:
      defaultZone: http://replica2:8003/eureka/