server:
  port: 8101
spring:
  security:
    user:
      name: admin
      password: 123456
  application:
    name: remote-service
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?useSSL=false&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: 1142165668
#    password: 1142165668
    hikari:
      maximum-pool-size: 4
      max-lifetime: 1770000
eureka:
  instance:
    # 续约间隔
    lease-renewal-interval-in-seconds: 30


  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8004/eureka/
    # 服务拉取间隔
    registry-fetch-interval-seconds: 30

#logging:
#  level:
#    com.mirco.remoteservice.controller.UserController: info